const homeCarsoulImg = [
  {
    name: "heart",
    fancy: [
      "./img/home/heart/fancy_01.webp",
      "./img/home/heart/fancy_02.webp",
      "./img/home/heart/fancy_03.webp",
      "./img/home/heart/fancy_04.webp",
      "./img/home/heart/fancy_05.webp",
      "./img/home/heart/fancy_06.webp",
      "./img/home/heart/fancy_07.webp",
      "./img/home/heart/fancy_08.webp",
      "./img/home/heart/fancy_09.webp",
    ],
    small: [
      "./img/home/heart/small_01.webp",
      "./img/home/heart/small_02.webp",
      "./img/home/heart/small_03.webp",
      "./img/home/heart/small_04.webp",
      "./img/home/heart/small_05.webp",
      "./img/home/heart/small_06.webp",
      "./img/home/heart/small_07.webp",
      "./img/home/heart/small_08.webp",
      "./img/home/heart/small_09.webp",
    ],
  },
  {
    name: "pin",
    fancy: [
      "./img/home/pin/fancy_01.webp",
      "./img/home/pin/fancy_02.webp",
      "./img/home/pin/fancy_03.webp",
      "./img/home/pin/fancy_04.webp",
      "./img/home/pin/fancy_05.webp",
      "./img/home/pin/fancy_06.webp",
      "./img/home/pin/fancy_07.webp",
      "./img/home/pin/fancy_08.webp",
      "./img/home/pin/fancy_09.webp",
    ],
    small: [
      "./img/home/pin/small_01.webp",
      "./img/home/pin/small_02.webp",
      "./img/home/pin/small_03.webp",
      "./img/home/pin/small_04.webp",
      "./img/home/pin/small_05.webp",
      "./img/home/pin/small_06.webp",
      "./img/home/pin/small_07.webp",
      "./img/home/pin/small_08.webp",
      "./img/home/pin/small_09.webp",
    ],
  },
  {
    name: "read",
    fancy: [
      "./img/home/read/fancy_01.webp",
      "./img/home/read/fancy_02.webp",
      "./img/home/read/fancy_03.webp",
      "./img/home/read/fancy_04.webp",
      "./img/home/read/fancy_05.webp",
      "./img/home/read/fancy_06.webp",
      "./img/home/read/fancy_07.webp",
      "./img/home/read/fancy_08.webp",
      "./img/home/read/fancy_09.webp",
    ],
    small: [
      "./img/home/read/small_01.webp",
      "./img/home/read/small_02.webp",
      "./img/home/read/small_03.webp",
      "./img/home/read/small_04.webp",
      "./img/home/read/small_05.webp",
      "./img/home/read/small_06.webp",
      "./img/home/read/small_07.webp",
      "./img/home/read/small_08.webp",
      "./img/home/read/small_09.webp",
    ],
  },
];
