const homeCarsoulImg = [
  {
    name: "心世界",
    fancy: [
      "./img/home/心世界/fancy_01.webp",
      "./img/home/心世界/fancy_02.webp",
      "./img/home/心世界/fancy_03.webp",
      "./img/home/心世界/fancy_04.webp",
      "./img/home/心世界/fancy_05.webp",
      "./img/home/心世界/fancy_06.webp",
      "./img/home/心世界/fancy_07.webp",
      "./img/home/心世界/fancy_08.webp",
      "./img/home/心世界/fancy_09.webp",
    ],
    small: [
      "./img/home/心世界/small_01.webp",
      "./img/home/心世界/small_02.webp",
      "./img/home/心世界/small_03.webp",
      "./img/home/心世界/small_04.webp",
      "./img/home/心世界/small_05.webp",
      "./img/home/心世界/small_06.webp",
      "./img/home/心世界/small_07.webp",
      "./img/home/心世界/small_08.webp",
      "./img/home/心世界/small_09.webp",
    ],
  },
  {
    name: "品世界",
    fancy: [
      "./img/home/品世界/fancy_01.webp",
      "./img/home/品世界/fancy_02.webp",
      "./img/home/品世界/fancy_03.webp",
      "./img/home/品世界/fancy_04.webp",
      "./img/home/品世界/fancy_05.webp",
      "./img/home/品世界/fancy_06.webp",
      "./img/home/品世界/fancy_07.webp",
      "./img/home/品世界/fancy_08.webp",
      "./img/home/品世界/fancy_09.webp",
    ],
    small: [
      "./img/home/品世界/small_01.webp",
      "./img/home/品世界/small_02.webp",
      "./img/home/品世界/small_03.webp",
      "./img/home/品世界/small_04.webp",
      "./img/home/品世界/small_05.webp",
      "./img/home/品世界/small_06.webp",
      "./img/home/品世界/small_07.webp",
      "./img/home/品世界/small_08.webp",
      "./img/home/品世界/small_09.webp",
    ],
  },
  {
    name: "閱世界",
    fancy: [
      "./img/home/閱世界/fancy_01.webp",
      "./img/home/閱世界/fancy_02.webp",
      "./img/home/閱世界/fancy_03.webp",
      "./img/home/閱世界/fancy_04.webp",
      "./img/home/閱世界/fancy_05.webp",
      "./img/home/閱世界/fancy_06.webp",
      "./img/home/閱世界/fancy_07.webp",
      "./img/home/閱世界/fancy_08.webp",
      "./img/home/閱世界/fancy_09.webp",
    ],
    small: [
      "./img/home/閱世界/small_01.webp",
      "./img/home/閱世界/small_02.webp",
      "./img/home/閱世界/small_03.webp",
      "./img/home/閱世界/small_04.webp",
      "./img/home/閱世界/small_05.webp",
      "./img/home/閱世界/small_06.webp",
      "./img/home/閱世界/small_07.webp",
      "./img/home/閱世界/small_08.webp",
      "./img/home/閱世界/small_09.webp",
    ],
  },
];
