const project = [
  {
    id: "1",
    main: "品世界",
    des: "大北區盛世啟動，重陽價值大躍進！串連起南港生技聚落計畫、內科2.0計畫、北投士林科技園區、生態社子島計畫與及圓山新創聚落，台北科技廊帶全球聚焦，即將帶動產業全面升級。30年來，偉康機構低調務實，全心全意投入建築專業，追求創新，逐夢踏實，堅持「只想蓋好房子」的初衷，專心做好每個環節，重視客戶需求、施工品質與結構安全，一切努力只為了能自豪地說出：「買到偉康建築的人，是有福氣的」!",
    unit: "813.62",
    seat: "座北朝南",
    located: "三陽重陽重劃區",
    address: "新北市三重區集賢路155號",
    section: "住宅區",
    pattern: "2-3房",
    structure: "RC構造",
    floor: "地下4層/地上14樓",
    household: "110",
    bigPic: [
      "../img/project-content/project-content-inner-big.webp",
      "../img/project-content/project-content-inner-big.webp",
      "../img/project-content/project-content-inner-big.webp",
    ],
    smallPic: [
      "../img/project-content/project-content-inner-small-1.webp",
      "../img/project-content/project-content-inner-small-2.webp",
      "../img/project-content/project-content-inner-small-3.webp",
    ],
  },
  {
    id: "2",
    main: "心世界",
    des: "大北區盛世啟動，重陽價值大躍進！串連起南港生技聚落計畫、內科2.0計畫、北投士林科技園區、生態社子島計畫與及圓山新創聚落，台北科技廊帶全球聚焦，即將帶動產業全面升級。30年來，偉康機構低調務實，全心全意投入建築專業，追求創新，逐夢踏實，堅持「只想蓋好房子」的初衷，專心做好每個環節，重視客戶需求、施工品質與結構安全，一切努力只為了能自豪地說出：「買到偉康建築的人，是有福氣的」!",
    unit: "813.62",
    seat: "座北朝南",
    located: "三陽重陽重劃區",
    address: "新北市三重區集賢路155號",
    section: "住宅區",
    pattern: "2-3房",
    structure: "RC構造",
    floor: "地下4層/地上14樓",
    household: "110",
    bigPic: [
      "../img/project-content/project-content-inner-big.webp",
      "../img/project-content/project-content-inner-big.webp",
      "../img/project-content/project-content-inner-big.webp",
    ],
    smallPic: [
      "../img/project-content/project-content-inner-small-1.webp",
      "../img/project-content/project-content-inner-small-2.webp",
      "../img/project-content/project-content-inner-small-3.webp",
    ],
  },
  {
    id: "3",
    main: "閱世界",
    des: "大北區盛世啟動，重陽價值大躍進！串連起南港生技聚落計畫、內科2.0計畫、北投士林科技園區、生態社子島計畫與及圓山新創聚落，台北科技廊帶全球聚焦，即將帶動產業全面升級。30年來，偉康機構低調務實，全心全意投入建築專業，追求創新，逐夢踏實，堅持「只想蓋好房子」的初衷，專心做好每個環節，重視客戶需求、施工品質與結構安全，一切努力只為了能自豪地說出：「買到偉康建築的人，是有福氣的」!",
    unit: "813.62",
    seat: "座北朝南",
    located: "三陽重陽重劃區",
    address: "新北市三重區集賢路155號",
    section: "住宅區",
    pattern: "2-3房",
    structure: "RC構造",
    floor: "地下4層/地上14樓",
    household: "110",
    bigPic: [
      "../img/project-content/project-content-inner-big.webp",
      "../img/project-content/project-content-inner-big.webp",
      "../img/project-content/project-content-inner-big.webp",
    ],
    smallPic: [
      "../img/project-content/project-content-inner-small-1.webp",
      "../img/project-content/project-content-inner-small-2.webp",
      "../img/project-content/project-content-inner-small-3.webp",
    ],
  },
];
